import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { seasonAwardsApi } from '../services/api';
import type { SeasonAwardsResponse } from '../services/api';
import type { Season, SeasonAward } from '../types';
import './SeasonAwards.css';

interface SeasonAwardsProps {
  season: Season;
}

const AWARD_ICONS: Record<string, string> = {
  mvp: '\u{1F3C6}',
  longest_win_streak: '\u{1F525}',
  iron_man: '\u{1F4AA}',
  best_win_pct: '\u{1F4CA}',
  most_title_defenses: '\u{1F3C5}',
  custom: '\u{2B50}',
};

function AwardCard({ award }: { award: SeasonAward & { autoGenerated?: boolean } }) {
  const { t } = useTranslation();
  const icon = AWARD_ICONS[award.awardType] || AWARD_ICONS['custom'];

  return (
    <div className={`award-card ${award.awardType}`}>
      <div className="award-icon">{icon}</div>
      <div className="award-details">
        <h4 className="award-name">{award.name}</h4>
        <p className="award-wrestler">{award.wrestlerName || t('common.unknown')}</p>
        {award.description && <p className="award-description">{award.description}</p>}
        {award.value && (
          <span className="award-value">{award.value}</span>
        )}
      </div>
      {award.autoGenerated && (
        <span className="award-badge auto">{t('seasonAwards.auto')}</span>
      )}
    </div>
  );
}

export default function SeasonAwards({ season }: SeasonAwardsProps) {
  const { t } = useTranslation();
  const [data, setData] = useState<SeasonAwardsResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const abortController = new AbortController();

    const fetchAwards = async () => {
      try {
        setLoading(true);
        const result = await seasonAwardsApi.getAll(season.seasonId, abortController.signal);
        if (!abortController.signal.aborted) {
          setData(result);
        }
      } catch (err) {
        if (err instanceof Error && err.name !== 'AbortError') {
          setError(err.message);
        }
      } finally {
        if (!abortController.signal.aborted) {
          setLoading(false);
        }
      }
    };

    fetchAwards();
    return () => abortController.abort();
  }, [season.seasonId]);

  if (loading) return <div className="loading">{t('common.loading')}</div>;
  if (error) return <div className="error-message">{error}</div>;
  if (!data) return null;

  const hasAwards = data.autoAwards.length > 0 || data.customAwards.length > 0;

  if (!hasAwards) {
    return (
      <div className="season-awards">
        <h3>{t('seasonAwards.title')}</h3>
        <p className="no-awards">{t('seasonAwards.noAwards')}</p>
      </div>
    );
  }

  return (
    <div className="season-awards">
      <h3>{t('seasonAwards.title')}</h3>

      {data.autoAwards.length > 0 && (
        <div className="awards-section">
          <h4>{t('seasonAwards.autoAwards')}</h4>
          <div className="awards-grid">
            {data.autoAwards.map(award => (
              <AwardCard key={award.awardId} award={award} />
            ))}
          </div>
        </div>
      )}

      {data.customAwards.length > 0 && (
        <div className="awards-section">
          <h4>{t('seasonAwards.customAwards')}</h4>
          <div className="awards-grid">
            {data.customAwards.map(award => (
              <AwardCard key={award.awardId} award={award} />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
