import { APIGatewayProxyHandler } from 'aws-lambda';
import { dynamoDb, TableNames } from '../../lib/dynamodb';
import { success, badRequest, serverError } from '../../lib/response';

interface MatchRecord {
  matchId: string;
  seasonId?: string;
  participants: string[];
  winners?: string[];
  losers?: string[];
  status: string;
  date: string;
  isChampionship?: boolean;
  isTitleDefense?: boolean;
  championshipId?: string;
}

interface WrestlerRecord {
  wrestlerId: string;
  name: string;
}

interface ChampionshipHistoryRecord {
  championshipId: string;
  champion: string | string[];
  wonDate: string;
  lostDate?: string;
  defenses?: number;
}

interface AutoAward {
  awardId: string;
  seasonId: string;
  name: string;
  awardType: string;
  wrestlerId: string;
  wrestlerName: string;
  description: string;
  value: string;
  autoGenerated: true;
}

const MIN_MATCHES_FOR_WIN_PCT = 3;

function computeAutoAwards(
  seasonId: string,
  matches: MatchRecord[],
  wrestlers: WrestlerRecord[],
  championshipHistory: ChampionshipHistoryRecord[]
): AutoAward[] {
  const awards: AutoAward[] = [];
  const wrestlerMap = new Map(wrestlers.map(w => [w.wrestlerId, w.name]));

  const seasonMatches = matches.filter(
    m => m.seasonId === seasonId && m.status === 'completed'
  );

  if (seasonMatches.length === 0) return awards;

  // Stats per wrestler
  const stats = new Map<string, { wins: number; losses: number; matches: number }>();
  for (const match of seasonMatches) {
    for (const pid of match.participants) {
      if (!stats.has(pid)) stats.set(pid, { wins: 0, losses: 0, matches: 0 });
      const s = stats.get(pid)!;
      s.matches++;
      if (match.winners?.includes(pid)) s.wins++;
      if (match.losers?.includes(pid)) s.losses++;
    }
  }

  // MVP (most wins)
  let mvpId = '';
  let mvpWins = 0;
  for (const [pid, s] of stats) {
    if (s.wins > mvpWins) {
      mvpWins = s.wins;
      mvpId = pid;
    }
  }
  if (mvpId && mvpWins > 0) {
    awards.push({
      awardId: 'auto-mvp',
      seasonId,
      name: 'MVP',
      awardType: 'mvp',
      wrestlerId: mvpId,
      wrestlerName: wrestlerMap.get(mvpId) || 'Unknown',
      description: 'Most wins in the season',
      value: `${mvpWins} wins`,
      autoGenerated: true,
    });
  }

  // Longest Win Streak
  const sortedMatches = [...seasonMatches].sort(
    (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
  );
  const streaks = new Map<string, { current: number; best: number }>();
  for (const match of sortedMatches) {
    for (const pid of match.participants) {
      if (!streaks.has(pid)) streaks.set(pid, { current: 0, best: 0 });
      const s = streaks.get(pid)!;
      if (match.winners?.includes(pid)) {
        s.current++;
        if (s.current > s.best) s.best = s.current;
      } else {
        s.current = 0;
      }
    }
  }
  let streakId = '';
  let streakBest = 0;
  for (const [pid, s] of streaks) {
    if (s.best > streakBest) {
      streakBest = s.best;
      streakId = pid;
    }
  }
  if (streakId && streakBest > 1) {
    awards.push({
      awardId: 'auto-longest-win-streak',
      seasonId,
      name: 'Longest Win Streak',
      awardType: 'longest_win_streak',
      wrestlerId: streakId,
      wrestlerName: wrestlerMap.get(streakId) || 'Unknown',
      description: 'Longest consecutive win streak',
      value: `${streakBest} wins`,
      autoGenerated: true,
    });
  }

  // Iron Man (most matches)
  let ironManId = '';
  let ironManMatches = 0;
  for (const [pid, s] of stats) {
    if (s.matches > ironManMatches) {
      ironManMatches = s.matches;
      ironManId = pid;
    }
  }
  if (ironManId && ironManMatches > 0) {
    awards.push({
      awardId: 'auto-iron-man',
      seasonId,
      name: 'Iron Man',
      awardType: 'iron_man',
      wrestlerId: ironManId,
      wrestlerName: wrestlerMap.get(ironManId) || 'Unknown',
      description: 'Most matches competed in',
      value: `${ironManMatches} matches`,
      autoGenerated: true,
    });
  }

  // Best Win Percentage (min threshold)
  let bestPctId = '';
  let bestPct = 0;
  for (const [pid, s] of stats) {
    if (s.matches >= MIN_MATCHES_FOR_WIN_PCT) {
      const pct = s.wins / s.matches;
      if (pct > bestPct) {
        bestPct = pct;
        bestPctId = pid;
      }
    }
  }
  if (bestPctId && bestPct > 0) {
    awards.push({
      awardId: 'auto-best-win-pct',
      seasonId,
      name: 'Best Win Percentage',
      awardType: 'best_win_pct',
      wrestlerId: bestPctId,
      wrestlerName: wrestlerMap.get(bestPctId) || 'Unknown',
      description: `Best win rate (min ${MIN_MATCHES_FOR_WIN_PCT} matches)`,
      value: `${Math.round(bestPct * 100)}%`,
      autoGenerated: true,
    });
  }

  // Most Championship Defenses
  let defenseId = '';
  let defenseCount = 0;
  for (const record of championshipHistory) {
    const champId = Array.isArray(record.champion) ? record.champion[0] : record.champion;
    const defs = record.defenses || 0;
    if (defs > defenseCount) {
      defenseCount = defs;
      defenseId = champId;
    }
  }
  if (defenseId && defenseCount > 0) {
    awards.push({
      awardId: 'auto-most-title-defenses',
      seasonId,
      name: 'Most Championship Defenses',
      awardType: 'most_title_defenses',
      wrestlerId: defenseId,
      wrestlerName: wrestlerMap.get(defenseId) || 'Unknown',
      description: 'Most successful title defenses',
      value: `${defenseCount} defenses`,
      autoGenerated: true,
    });
  }

  return awards;
}

export const handler: APIGatewayProxyHandler = async (event) => {
  try {
    const seasonId = event.pathParameters?.seasonId;
    if (!seasonId) {
      return badRequest('Season ID is required');
    }

    // Fetch custom awards from DynamoDB
    const customResult = await dynamoDb.query({
      TableName: TableNames.SEASON_AWARDS,
      KeyConditionExpression: '#seasonId = :seasonId',
      ExpressionAttributeNames: { '#seasonId': 'seasonId' },
      ExpressionAttributeValues: { ':seasonId': seasonId },
    });
    const customAwards = (customResult.Items || []).map(item => ({
      ...item,
      autoGenerated: false,
    }));

    // Fetch data for auto-generated awards
    const [matchesResult, wrestlersResult, champHistResult] = await Promise.all([
      dynamoDb.scan({ TableName: TableNames.MATCHES }),
      dynamoDb.scan({ TableName: TableNames.WRESTLERS }),
      dynamoDb.scan({ TableName: TableNames.CHAMPIONSHIP_HISTORY }),
    ]);

    const autoAwards = computeAutoAwards(
      seasonId,
      (matchesResult.Items || []) as unknown as MatchRecord[],
      (wrestlersResult.Items || []) as unknown as WrestlerRecord[],
      (champHistResult.Items || []) as unknown as ChampionshipHistoryRecord[]
    );

    return success({
      seasonId,
      autoAwards,
      customAwards,
    });
  } catch (err) {
    console.error('Error fetching season awards:', err);
    return serverError('Failed to fetch season awards');
  }
};

export { computeAutoAwards };
