import type { SeasonAward } from '../../types';
import { API_BASE_URL, fetchWithAuth } from './apiClient';

export interface SeasonAwardsResponse {
  seasonId: string;
  autoAwards: (SeasonAward & { autoGenerated: true })[];
  customAwards: (SeasonAward & { autoGenerated: false })[];
}

export const seasonAwardsApi = {
  getAll: async (seasonId: string, signal?: AbortSignal): Promise<SeasonAwardsResponse> => {
    return fetchWithAuth(`${API_BASE_URL}/seasons/${seasonId}/awards`, {}, signal);
  },

  create: async (seasonId: string, award: { name: string; wrestlerId: string; description?: string }): Promise<SeasonAward> => {
    return fetchWithAuth(`${API_BASE_URL}/seasons/${seasonId}/awards`, {
      method: 'POST',
      body: JSON.stringify(award),
    });
  },

  delete: async (seasonId: string, awardId: string): Promise<void> => {
    return fetchWithAuth(`${API_BASE_URL}/seasons/${seasonId}/awards/${awardId}`, {
      method: 'DELETE',
    });
  },
};
